### ISSUE TITLE
Add metrics for images failing version-check

### ISSUE THREAD

**Issue by MPV** [jetstack/version-checker#74] opened 2021-02-04 10:59 UTC
Today version-checker keeps logging when it fails on some image.

Wouldn't it be nice having a metric for this?

Maybe something like `version_checker_image_failed_count`?
(with labels similar to the `version_checker_is_latest_version` metric — such as; container, image, exported_namespace, exported_pod)

Then you could be alerted when there's images that fail the version-check. That would prompt you to check the logs for further details.

**Comment by davidcollom** [comment] 2023-07-12 11:33
Closing as I think this is a duplicate of #82.

**Closed by davidcollom** 2023-07-12 11:33 UTC
